apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ${NAME}${SUFFIX}
spec:
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    deploymentconfig: ${NAME}${SUFFIX}
  sessionAffinity: None
  type: ClusterIP
