apiVersion: v1
kind: Template
metadata:
  name: ${NAME}-template
labels:
  template: ${NAME}
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    ports:
    - name: api
      port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    sessionAffinity: None
    type: ClusterIP
    parameters:
    - description: A name used for all objects
      displayName: Name
      name: NAME
      required: true
      value: bcgw-poc
    - description: A name suffix used for all objects
      displayName: Suffix
      name: SUFFIX
      required: false
      value: -api    
